# Generated by Django 5.2.1 on 2025-06-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_delivered_message_seen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='seen',
        ),
    ]
