# Generated by Django 5.2.1 on 2025-06-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_voicemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicemessage',
            name='message',
        ),
        migrations.DeleteModel(
            name='MessageReaction',
        ),
        migrations.DeleteModel(
            name='VoiceMessage',
        ),
    ]
